name: 'Andysworld!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33147057448513806
title: 'Andysworld!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fbda28'
    - '#b19732'
    - '#9a1201'
    - '#3c5691'
  brandStrength: 1
  lightness: 0.5589572796598077
  saturation: 0.6359415834303945
  rhythmicContrast: 0.6975403092801571
purpose: []
