name: 'Andysworld!'
favicon: null
layout_spectrum: 0.899438199819997
typography_spectrum: 0.33147057448513806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.14133416023105383
  lightness: 0.5589572796598077
  saturation: 0.6359415834303945
  rhythmicContrast: 0.6975403092801571
purpose: []
